// Zone shortname → display name table for Brewall's EverQuest map pack.
// These names are used twice:
//   1. shown in the UI (search, panel, graph nodes)
//   2. normalized and matched against "to_..." point labels to resolve
//      zone connections at build time.
// Zones missing from this table get a prettified shortname as a fallback.

export const ZONE_NAMES = {
  // ---- Classic: Antonica ----
  qeynos: 'South Qeynos',
  qeynos2: 'North Qeynos',
  qcat: 'The Qeynos Aqueduct System',
  qeytoqrg: 'Qeynos Hills',
  qrg: 'Surefall Glade',
  blackburrow: 'Blackburrow',
  everfrost: 'Everfrost Peaks',
  halas: 'Halas',
  permafrost: 'Permafrost Keep',
  eastkarana: 'East Karana',
  northkarana: 'North Karana',
  southkarana: 'South Karana',
  qey2hh1: 'West Karana',
  highpass: 'Highpass Hold',
  highkeep: 'HighKeep',
  highpasshold: 'Highpass Hold (Revamp)',
  highpasskeep: 'HighKeep (Revamp)',
  kithicor: 'Kithicor Forest',
  rivervale: 'Rivervale',
  misty: 'Misty Thicket',
  mistythicket: 'Misty Thicket (Revamp)',
  runnyeye: 'Clan RunnyEye',
  beholder: 'Gorge of King Xorbb',
  commons: 'West Commonlands',
  ecommons: 'East Commonlands',
  commonlands: 'The Commonlands (Revamp)',
  freporte: 'East Freeport',
  freportn: 'North Freeport',
  freportw: 'West Freeport',
  freeporteast: 'East Freeport (Revamp)',
  freeportwest: 'West Freeport (Revamp)',
  freeportacademy: 'Academy of Arcane Science',
  freeportarena: 'Freeport Arena',
  freeportcityhall: 'Freeport City Hall',
  freeporthall: 'Freeport Hall of Truth',
  freeportmilitia: 'Freeport Militia House',
  freeportsewers: 'Freeport Sewers',
  freeporttheater: 'Freeport Theater of the Tranquil',
  nro: 'North Ro',
  sro: 'South Ro',
  northro: 'North Ro (Revamp)',
  southro: 'South Ro (Revamp)',
  oasis: 'Oasis of Marr',
  innothule: 'Innothule Swamp',
  innothuleb: 'Innothule Swamp (Revamp)',
  feerrott: 'The Feerrott',
  guktop: 'Upper Guk',
  gukbottom: 'Lower Guk',
  grobb: 'Grobb',
  oggok: 'Oggok',
  rathemtn: 'Rathe Mountains',
  lakerathe: 'Lake Rathetear',
  arena: 'The Arena',
  arena2: 'The Arena Two',
  cazicthule: 'Temple of Cazic-Thule',
  neriaka: 'Neriak Foreign Quarter',
  neriakb: 'Neriak Commons',
  neriakc: 'Neriak Third Gate',
  neriakd: 'Neriak Fourth Gate',
  nektulos: 'Nektulos Forest',
  lavastorm: 'Lavastorm Mountains',
  najena: 'Najena',
  soldunga: "Solusek's Eye",
  soldungb: "Nagafen's Lair",
  soldungc: 'The Caverns of Exile',
  soltemple: 'Temple of Solusek Ro',
  solrotower: 'Tower of Solusek Ro',
  befallen: 'Befallen',
  befallenb: 'Befallen (Revamp)',
  kedge: 'Kedge Keep',
  cauldron: "Dagnor's Cauldron",
  unrest: 'Estate of Unrest',
  butcher: 'Butcherblock Mountains',
  kaladima: 'North Kaladim',
  kaladimb: 'South Kaladim',
  gfaydark: 'Greater Faydark',
  lfaydark: 'Lesser Faydark',
  crushbone: 'Clan Crushbone',
  felwithea: 'Northern Felwithe',
  felwitheb: 'Southern Felwithe',
  akanon: "Ak'Anon",
  steamfont: 'Steamfont Mountains',
  steamfontmts: 'Steamfont Mountains (Revamp)',
  mistmoore: 'Castle Mistmoore',
  oot: 'Ocean of Tears',
  oceanoftears: 'Ocean of Tears (Revamp)',
  erudnext: 'Erudin',
  erudnint: 'Erudin Palace',
  erudsxing: "Erud's Crossing",
  erudsxing2: "Erud's Crossing (Revamp)",
  tox: 'Toxxulia Forest',
  toxxulia: 'Toxxulia Forest (Revamp)',
  kerraridge: 'Kerra Isle',
  paineel: 'Paineel',
  hole: 'The Hole',
  stonebrunt: 'Stonebrunt Mountains',
  warrens: 'The Warrens',
  jaggedpine: 'Jaggedpine Forest',
  nedaria: "Nedaria's Landing",
  kithforest: 'Kithicor Forest (SoD)',

  // ---- Classic: Planes ----
  hateplane: 'Plane of Hate',
  hateplaneb: 'Plane of Hate (Revamp)',
  fearplane: 'Plane of Fear',
  airplane: 'Plane of Sky',
  growthplane: 'Plane of Growth',
  mischiefplane: 'Plane of Mischief',

  // ---- Kunark ----
  fieldofbone: 'Field of Bone',
  cabwest: 'West Cabilis',
  cabeast: 'East Cabilis',
  swampofnohope: 'Swamp of No Hope',
  kurn: "Kurn's Tower",
  warslikswood: 'Warsliks Woods',
  lakeofillomen: 'Lake of Ill Omen',
  frontiermtns: 'Frontier Mountains',
  dreadlands: 'Dreadlands',
  burningwood: 'Burning Woods',
  skyfire: 'Skyfire Mountains',
  overthere: 'The Overthere',
  firiona: 'Firiona Vie',
  kaesora: 'Kaesora',
  sebilis: 'Old Sebilis',
  citymist: 'City of Mist',
  dalnir: 'Crypt of Dalnir',
  charasis: 'Howling Stones',
  charasisb: 'Howling Stones (B)',
  chardok: 'Chardok',
  chardokb: 'Chardok: Halls of Betrayal',
  nurga: 'Mines of Nurga',
  droga: 'Temple of Droga',
  emeraldjungle: 'Emerald Jungle',
  trakanon: "Trakanon's Teeth",
  timorous: 'Timorous Deep',
  karnor: "Karnor's Castle",
  veeshan: "Veeshan's Peak",
  veksar: 'Veksar',

  // ---- Velious ----
  iceclad: 'Iceclad Ocean',
  frozenshadow: 'Tower of Frozen Shadow',
  eastwastes: 'Eastern Wastes',
  greatdivide: 'Great Divide',
  thurgadina: 'Thurgadin',
  thurgadinb: 'Icewell Keep',
  kael: 'Kael Drakkel',
  wakening: 'Wakening Land',
  westwastes: 'Western Wastes',
  cobaltscar: 'Cobalt Scar',
  sirens: "Siren's Grotto",
  velketor: "Velketor's Labyrinth",
  crystal: 'Crystal Caverns',
  necropolis: 'Dragon Necropolis',
  templeveeshan: 'Temple of Veeshan',
  skyshrine: 'Skyshrine',
  sleeper: "Sleeper's Tomb",

  // ---- Luclin ----
  nexus: 'The Nexus',
  bazaar: 'The Bazaar',
  shadowhaven: 'Shadow Haven',
  sharvahl: 'Shar Vahl',
  paludal: 'Paludal Caverns',
  hollowshade: 'Hollowshade Moor',
  grimling: 'Grimling Forest',
  tenebrous: 'Tenebrous Mountains',
  maiden: "Maiden's Eye",
  dawnshroud: 'Dawnshroud Peaks',
  katta: 'Katta Castellum',
  netherbian: 'Netherbian Lair',
  ssratemple: 'Ssraeshza Temple',
  griegsend: "Grieg's End",
  thedeep: 'The Deep',
  fungusgrove: 'Fungus Grove',
  twilight: 'Twilight Sea',
  thegrey: 'The Grey',
  scarlet: 'Scarlet Desert',
  umbral: 'Umbral Plains',
  akheva: 'Akheva Ruins',
  echo: 'Echo Caverns',
  shadeweaver: "Shadeweaver's Thicket",
  acrylia: 'Acrylia Caverns',
  sseru: 'Sanctus Seru',
  mseru: 'Marus Seru',
  vexthal: 'Vex Thal',
  letalis: 'Mons Letalis',

  // ---- Planes of Power ----
  poknowledge: 'Plane of Knowledge',
  potranquility: 'Plane of Tranquility',
  ponightmare: 'Plane of Nightmare',
  podisease: 'Plane of Disease',
  poinnovation: 'Plane of Innovation',
  potorment: 'Plane of Torment',
  povalor: 'Plane of Valor',
  postorms: 'Plane of Storms',
  hohonora: 'Halls of Honor',
  hohonorb: 'Temple of Marr',
  pojustice: 'Plane of Justice',
  potactics: 'Drunder, Fortress of Zek',
  poair: 'Eryslai, Kingdom of Wind',
  powater: 'Reef of Coirnav',
  pofire: 'Doomfire, the Burning Lands',
  poeartha: 'Vegarlson, the Earthen Badlands',
  poearthb: 'Ragrax, Stronghold of the Twelve',
  potimea: 'Plane of Time A',
  potimeb: 'Plane of Time B',
  codecay: 'Crypt of Decay',
  codecayb: 'Crypt of Decay (TBM)',
  bothunder: 'Bastion of Thunder',
  powar: 'Plane of War',

  // ---- Legacy of Ykesha ----
  gunthak: 'Gulf of Gunthak',
  dulak: "Dulak's Harbor",
  torgiran: 'Torgiran Mines',
  nadox: 'Crypt of Nadox',
  hatesfury: "Hate's Fury",

  // ---- Gates of Discord ----
  natimbi: 'Natimbi, the Broken Shores',
  qinimi: 'Qinimi, Court of Nihilia',
  riwwi: 'Riwwi, Coliseum of Games',
  barindu: 'Barindu, Hanging Gardens',
  ferubi: 'Ferubi, Forgotten Temple of Taelosia',
  kodtaz: "Kod'Taz, Broken Trial Grounds",
  ikkinz: 'Ikkinz, Chambers of Transcendence',
  qvic: 'Qvic, Prayer Grounds of Calling',
  qvicb: 'Qvic (B)',
  inktuta: "Inktu'Ta, the Unmasked Chapel",
  txevu: 'Txevu, Lair of the Elite',
  tacvi: 'Tacvi, Seat of the Slaver',
  tipt: 'Tipt, Treacherous Crags',
  vxed: 'Vxed, the Crumbling Caverns',
  yxtta: 'Yxtta, Pulpit of Exiles',
  uqua: 'Uqua, the Ocean God Chantry',
  abysmal: 'Abysmal Sea',
  barter: 'The Barter Hall',

  // ---- Omens of War ----
  wallofslaughter: 'Wall of Slaughter',
  bloodfields: 'The Bloodfields',
  draniksscar: "Dranik's Scar",
  causeway: "Nobles' Causeway",
  dranik: 'Ruined City of Dranik',
  riftseekers: "Riftseekers' Sanctum",
  anguish: 'Asylum of Anguish',
  provinggrounds: 'Muramite Proving Grounds',
  harbingers: "Harbinger's Spire",

  // ---- Dragons of Norrath ----
  broodlands: 'The Broodlands',
  stillmoona: 'Stillmoon Temple',
  stillmoonb: 'The Ascent',
  thenest: 'The Accursed Nest',
  thundercrest: 'Thundercrest Isles',
  delvea: "Lavaspinner's Lair",
  delveb: "Tirranun's Delve",
  guardian: 'The Guardian',

  // ---- Depths of Darkhollow ----
  dreadspire: 'Dreadspire Keep',
  drachnidhive: 'The Hive',
  drachnidhivea: 'The Hive (A)',
  drachnidhiveb: 'The Hive (B)',
  drachnidhivec: 'The Hive (C)',
  westkorlach: 'Stoneroot Falls',
  eastkorlach: 'The Undershore',
  illsalin: 'Ruins of Illsalin',
  shadowspine: 'Shadow Spine',
  corathus: 'Corathus Creep',

  // ---- Prophecy of Ro ----
  arcstone: 'Arcstone, Isle of Spirits',
  relic: 'Relic, the Artifact City',
  skylance: 'Skylance',
  devastation: 'The Devastation',
  rage: 'Sverag, Stronghold of Rage',
  takishruins: 'Ruins of Takish-Hiz',
  takishruinsa: 'Ruins of Takish-Hiz (A)',
  elddar: 'The Elddar Forest',
  elddara: 'The Elddar Forest (A)',
  theater: 'Theater of Blood',
  theatera: 'Theater of Blood (A)',

  // ---- The Serpent's Spine ----
  crescent: 'Crescent Reach',
  moors: 'Blightfire Moors',
  stonehive: 'Stone Hive',
  mesa: 'Goru`kar Mesa',
  sunderock: 'Sunderock Springs',
  vergalid: 'Vergalid Mines',
  direwind: 'Direwind Cliffs',
  ashengate: 'Ashengate, Reliquary of the Scale',
  frostcrypt: 'Frostcrypt, Throne of the Shade King',
  valdeholm: 'Valdeholm',
  icefall: 'Icefall Glacier',
  steppes: 'The Steppes',
  roost: 'Blackfeather Roost',

  // ---- The Buried Sea ----
  barren: 'Barren Coast',
  buriedsea: 'The Buried Sea',
  jardelshook: "Jardel's Hook",
  monkeyrock: 'Monkey Rock',
  blacksail: 'Blacksail Folly',
  maidensgrave: "Maiden's Grave",
  redfeather: 'Redfeather Isle',
  suncrest: 'Suncrest Isle',
  brotherisland: 'Brother Island',
  kattacastrum: 'Katta Castrum',
  kattacastrumb: 'Katta Castrum: Deluge',
  thalassius: 'Thalassius, the Coral Keep',
  zhisza: 'Zhisza, the Shissar Sanctuary',
  silyssar: 'Silyssar, New Chelsith',
  solteris: 'Solteris, the Throne of Ro',
  atiiki: 'Jewel of Atiiki',

  // ---- Secrets of Faydwer ----
  dragonscale: 'Dragonscale Hills',
  dragonscalea: "Deepscar's Den",
  dragonscaleb: "Tinmizer's Wunderwerks",
  mechanotus: 'Fortress Mechanotus',
  gyrospireb: 'Gyrospire Beza',
  gyrospirez: 'Gyrospire Zeka',
  steamfactory: 'The Steam Factory',
  hillsofshade: 'Hills of Shade',
  bloodmoon: 'Bloodmoon Keep',
  crystallos: 'Crystallos, Lair of the Awakened',
  cryptofshade: 'Crypt of Shade',
  lopingplains: 'Loping Plains',
  mansion: "Meldrath's Majestic Mansion",
  gnomemtn: 'Gnome Memorial Mountain',

  // ---- Seeds of Destruction ----
  oceangreenhills: 'Oceangreen Hills',
  oceangreenvillage: 'Oceangreen Village',
  oldblackburrow: 'Blackburrow (SoD)',
  oldbloodfield: 'Old Bloodfields',
  bloodmoonb: 'Bloodmoon Keep (B)',
  korascian: 'Korascian Warrens',
  rathechamber: 'Rathe Council Chambers',
  toskirakk: 'Toskirakk',
  oldfieldofbone: 'Field of Scale',
  oldfieldofboneb: 'Field of Scale (B)',
  oldkaesoraa: 'Kaesora Library',
  oldkaesorab: 'Kaesora Hatchery',
  oldkurn: "Kurn's Stronghold",
  oldkithicor: 'Bloody Kithicor',
  oldcommons: 'Old Commonlands',
  olddranik: 'City of Dranik (SoD)',
  precipiceofwar: 'The Precipice of War',
  discord: 'The Plane of Discord',
  discordtower: 'Tower of Discord',
  bloodfalls: 'Blood Falls',

  // ---- Underfoot ----
  brellsrest: "Brell's Rest",
  coolingchamber: 'The Cooling Chamber',
  underquarry: 'The Underquarry',
  arthicrex: 'Arthicrex',
  foundation: 'The Foundation',
  lichencreep: 'Lichen Creep',
  pellucid: 'Pellucid Grotto',
  convorteum: 'The Convorteum',
  brellsarena: "Brell's Arena",
  fungalforest: 'Fungal Forest',
  shiningcity: 'Kernagir, the Shining City',
  brellstemple: "Brell's Temple",

  // ---- House of Thule ----
  feerrott2: 'The Feerrott, Dream of Thule',
  alkabormare: "Al'Kabor's Nightmare",
  morellcastle: "Morell's Castle",
  somnium: 'Sanctum Somnium',
  eastsepulcher: 'Sepulcher East',
  westsepulcher: 'Sepulcher West',
  sepulcher: 'Sepulcher of Order',
  thulehouse1: 'House of Thule',
  thulehouse2: 'House of Thule, Upper Floors',
  thulelibrary: 'The Library',
  well: 'The Well',
  miragulmare: "Miragul's Nightmare",
  fhalls: 'The Fungal Halls',

  // ---- Veil of Alaris ----
  argath: 'Argath, Bastion of Illdaera',
  sarithcity: 'Sarith, City of Tides',
  rubak: 'Rubak Oseka, Temple of the Sea',
  beastdomain: "Beasts' Domain",
  resplendent: 'Resplendent Temple',
  pillarsalra: 'Pillars of Alra',
  windsong: 'Windsong Sanctuary',
  cityofbronze: 'Erillion, City of Bronze',

  // ---- Rain of Fear ----
  shardslanding: "Shard's Landing",
  xorbb: 'Valley of King Xorbb',
  kaelshard: "Kael Drakkel: The King's Madness",
  eastwastesshard: "East Wastes: Zeixshi-Kar's Awakening",
  crystalshard: 'Crystal Caverns: Fragment of Fear',
  breedinggrounds: 'The Breeding Grounds',
  eviltree: 'Evantil, the Vile Oak',
  grelleth: "Grelleth's Palace",
  chelsithreborn: 'Chelsith Reborn',
  heartoffear: 'Heart of Fear',
  heartoffearb: 'Heart of Fear (B)',
  heartoffearc: 'Heart of Fear (C)',

  // ---- Call of the Forsaken ----
  ethernere: 'Ethernere Tainted West Karana',
  deadhills: 'The Dead Hills',
  bixiewarfront: 'Bixie Warfront',
  towerofrot: 'Tower of Rot',
  arginhiz: 'Argin-Hiz',

  // ---- The Darkened Sea ----
  tempesttemple: 'Tempest Temple',
  endlesscaverns: 'Caverns of Endless Song',
  degmar: 'Degmar, the Lost Castle',
  thuliasaur: 'Thuliasaur Island',
  arxmentis: 'Arx Mentis',

  // ---- The Broken Mirror ----
  pohealth: 'Plane of Health',
  cshome: 'Sul Vius: Demiplane of Life',
  cosul: 'Crypt of Sul',

  // ---- Empires of Kunark ----
  scorchedwoods: 'The Scorched Woods',
  frontiermtnsb: 'Frontier Mountains (EoK)',
  lceanium: 'Lceanium',
  charasistwo: 'Howling Stones (EoK)',
  overtheretwo: 'The Overthere (EoK)',
  drogab: 'Temple of Droga (EoK)',
  korshaext: 'Kor-Sha Laboratory',
  korshaint: 'Kor-Sha Laboratory (Interior)',
  chardoktwo: 'Chardok (EoK)',
  gorowyn: 'Gorowyn',

  // ---- Ring of Scale ----
  veeshantwo: "Veeshan's Peak (RoS)",
  skyfiretwo: 'Skyfire Mountains (RoS)',

  // ---- The Burning Lands ----
  stratos: "Stratos: Zephyr's Flight",
  aalishai: 'Aalishai: Palace of Embers',
  empyr: 'Empyr: Realms of Ash',
  esianti: 'Esianti: Palace of the Winds',
  mearatas: 'Mearatas: The Stone Demesne',
  trialsofsmoke: 'Trials of Smoke',
  chamberoftears: 'Chamber of Tears',

  // ---- Torment of Velious / Claws of Veeshan ----
  eastwastestwo: 'Eastern Wastes (ToV)',
  greatdividetwo: 'Great Divide (ToV)',
  kaeltwo: 'Kael Drakkel (ToV)',
  crystaltwoa: 'Crystal Caverns (ToV)',
  crystaltwob: 'Crystal Caverns (ToV) (B)',
  velketortwo: "Velketor's Labyrinth (ToV)",
  templeveeshantwo: 'Temple of Veeshan (ToV)',
  sleepertwo: "Sleeper's Tomb (ToV)",
  frozenshadowtwo: 'Tower of Frozen Shadow (ToV)',
  cobaltscartwo: 'Cobalt Scar (CoV)',
  westwastestwo: 'Western Wastes (CoV)',
  skyshrinetwo: 'Skyshrine (CoV)',

  // ---- Terror of Luclin ----
  maidentwo: "Maiden's Eye (ToL)",
  umbraltwo: 'Umbral Plains (ToL)',
  shadowhaventwo: 'Shadow Haven (ToL)',
  shadeweavertwo: "Shadeweaver's Tangle",
  basilica: 'Basilica of Adumbration',
  vexthaltwo: 'Vex Thal (ToL)',
  akhevatwo: 'Ka Vethan',

  // ---- Night of Shadows ----
  shadowvalley: 'Shadow Valley',
  darklightcaverns: 'Darklight Caverns',
  deepshade: 'Deepshade',
  firefallpass: 'Firefall Pass',
  paludaltwo: 'Paludal Caverns (NoS)',
  sharvahltwo: 'Shar Vahl, Divided',
  sharvaltwo: 'Shar Vahl, Divided (B)',

  // ---- Laurion's Song ----
  laurioninn: 'Laurion Inn',
  herosforge: "Hero's Forge",
  ankexfen: 'Ankexfen Keep',
  pallomen: "Pal'Lomen",
  timorousfalls: 'Timorous Falls',
  moorsofnokk: 'Moors of Nokk',
  unkemptwoods: 'The Unkempt Woods',

  // ---- The Outer Brood ----
  aureatecovert: 'Aureate Covert',

  // ---- Misc / utility ----
  guildlobby: 'Guild Lobby',
  guildhall: 'Guild Hall',
  guildhalllrg: 'Grand Guild Hall',
  guildhallsml: 'Modest Guild Hall',
  neighborhood: 'Sunrise Hills',
  tutorial: 'Mines of Gloomingdeep',
  tutoriala: 'Mines of Gloomingdeep (A)',
  tutorialb: 'Mines of Gloomingdeep (B)',
  weddingchapel: 'Wedding Chapel',
  weddingchapeldark: 'Wedding Chapel (Dark)',
  hodstock: 'Hodstock Hills',
  brellsarena2: "Brell's Arena (B)",
  thurgadina1: 'Thurgadin (Alternate)',
  nektulos_original: 'Nektulos Forest (Original)',
  lavastorm_original: 'Lavastorm Mountains (Original)',
};

// LDoN / instanced wing sets share a base name plus a wing letter; generate
// them rather than typing 40 entries.
const WING_SETS = [
  ['guk', 'Deepest Guk'],
  ['ruj', 'Rujarkian Hills'],
  ['tak', 'Takish-Hiz'],
  ['mir', "Miragul's Menagerie"],
  ['mmc', 'Mistmoore Catacombs'],
  ['chambers', 'Muramite Trial Chambers'],
  ['thevoid', 'The Void'],
  ['dranikcatacombs', 'Catacombs of Dranik'],
  ['dranikhollows', 'Hollows of Dranik'],
  ['draniksewers', 'Sewers of Dranik'],
  ['illsalin', 'Ruins of Illsalin'],
  ['westkorlach', 'Stoneroot Falls'],
  ['eastkorlach', 'The Undershore'],
  ['devastation', 'The Devastation'],
  ['corathus', 'Corathus Creep'],
];
for (const [prefix, base] of WING_SETS) {
  for (const letter of 'abcdefghij') {
    const short = prefix + letter;
    if (!ZONE_NAMES[short]) ZONE_NAMES[short] = `${base} (${letter.toUpperCase()})`;
  }
}

// Explicit label → shortname overrides, keyed by NORMALIZED label text
// (lowercased, parentheticals dropped, "the " prefix dropped, alphanumerics
// only). Used when a "to_..." label doesn't literally match a zone name, or
// when it's ambiguous and we want a specific era's zone (EQ Legends runs
// classic-era content, so classic zones win).
export const ALIASES = {
  freeport: 'freportw',
  eastfreeport: 'freporte',
  westfreeport: 'freportw',
  northfreeport: 'freportn',
  qeynos: 'qeynos',
  cabilis: 'cabwest',
  neriak: 'neriaka',
  erudin: 'erudnext',
  felwithe: 'felwithea',
  kaladim: 'kaladima',
  kelethin: 'gfaydark',
  butcherblock: 'butcher',
  toxxulia: 'tox',
  pok: 'poknowledge',
  planeofknowledge: 'poknowledge',
  karana: 'northkarana',
  guk: 'guktop',
  overthere: 'overthere',
  greatdivide: 'greatdivide',
  gloomingdeep: 'tutorialb',
  // longname variants / renames / map-file typos (all keys pre-normalized:
  // lowercased, no "the", alphanumerics only)
  northdesertofro: 'nro',
  northerndesertofro: 'nro',
  southdesertofro: 'sro',
  southerndesertofro: 'sro',
  planeoftime: 'potimea',
  cityofguk: 'guktop',
  ruinsofoldguk: 'gukbottom',
  cabiliseast: 'cabeast',
  cabiliswest: 'cabwest',
  easternplainsofkarana: 'eastkarana',
  northernplainsofkarana: 'northkarana',
  southernplainsofkarana: 'southkarana',
  westernplainsofkarana: 'qey2hh1',
  liberatedcitadelofrunnyeye: 'runnyeye',
  cityofthurgadin: 'thurgadina',
  theaterofeternity: 'toe',
  castleofmistmoore: 'mistmoore',
  nekulosforest: 'nektulos', // map-file typo
  cavernsofexcile: 'soldungc', // map-file typo
  feerott: 'feerrott', // map-file typo
  fortressmechantos: 'mechanotus', // map-file typo
  ruinsofshadowhaven: 'shadowhaventwo',
  ruinsoflxanvom: 'codecay',
  gukta: 'grobb', // Grobb was renamed Gukta during the frog era
  paludaldepths: 'paludaltwo',
  gatesofkorsha: 'korshaext',
  houseofthuleupper: 'thulehouse2',
};
